### PR TITLE
add release v1.2 data

### PR DESCRIPTION
**Pull request by alaypatel07**
The gray dotted line in the graph is March 1, 2023, denoting release of v0.60
The blue dotted line in the graph is July 6, 2023, denoting release of v1.0.0
The green dotted line in the graph is September 6, 2023, denoting change in k8s provider from v1.25 to v1.27
The red dotted line in the graph is December 25, 2023, denoting release of v1.1.0

### CODE REVIEW

**Comment by alaypatel07** [comment]
newplot (2)

**Comment by alaypatel07** [comment]
cc @rthallisey

**Comment by fabiand** [comment]
Wow! What improvements you have made over the past year! Crazy. Kudos.

**Pull request merged**
